# Generated by Tibia. GPL-3.0-or-later.
BUNDLE_NAME := {{=it.product.bundleName}}
{{~["commonDir", "dataDir", "pluginDir", "apiDir", "mkincDir"] :key}}
{{?it.perone_make?.[key] || it.make?.[key]}}
{{=key.replace(/Dir$/, "_DIR").toUpperCase()}} := {{=it.perone_make?.[key] ?? it.make?.[key]}}
{{?}}
{{~}}
{{=it.make?.extra || ""}}
{{=it.perone_make?.extra || ""}}
